---
- name: Install AWS CLI
  become: yes
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm -rf aws
    rm awscliv2.zip
  args:
    creates: "/usr/local/bin/aws"
