---
- name: "Query package: {{ item.name }}"
  command: "dpkg-query -W {{ item.name }}"
  register: query_package
  failed_when: false
  changed_when: query_package.rc == 1

- block:
    - name: "Download {{ item.name }}"
      get_url:
        url: "{{ item.url }}"
        dest: "{{ ansible_env.HOME }}/Downloads/{{ item.name }}-x.x.x.deb"

    - name: "Install {{ item.name }}"
      become: yes
      apt:
        state: present
        deb: "{{ansible_env.HOME}}/Downloads/{{ item.name }}-x.x.x.deb"
  when: query_package.rc == 1

- name: "Delete {{ item.name }}-x.x.x.deb"
  file:
    path: "{{ ansible_env.HOME }}/Downloads/{{ item.name }}-x.x.x.deb"
    state: absent
