---
- name: Install `lazydocker`
  become: no
  shell: >
    curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/lazydocker"
