---
- name: Install `ca-certificates, curl, gnupg & lsb-release`
  become: yes
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker’s official GPG key
  become: yes
  shell: |
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Setup the repository
  become: yes
  shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install `docker-ce, docker-ce-cli, docker-compose-plugin, containerd.io`
  become: yes
  apt:
    update_cache: true
    state: present
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io 
    - docker-compose-plugin
