window:
  opacity: 0.96
  dynamic_title: true
  decorations_theme_variant: None
  padding:
    x: 8
    y: 8

cursor:
  blink_interval: 750
  blink_timeout: 5
  unfocused_hollow: true
  style:
    shape: Beam
    blinking: On

font:
  size: 10.25
  builtin_box_drawing: false
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Medium Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  draw_bold_text_with_bright_colors: true

shell:
  program: /bin/bash
  args:
    - -l
    - -c
    - "tmux attach || tmux"

env:
  TERM: xterm-256color

colors:
  # https://github.com/zatchheems/tokyo-night-alacritty-theme
  primary:
    background: '0x1a1b26'
    foreground: '0xa9b1d6'

  # Normal colors
  normal:
    black:   '0x32344a'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0x787c99'

  # Bright colors
  bright:
    black:   '0x444b6a'
    red:     '0xff7a93'
    green:   '0xb9f27c'
    yellow:  '0xff9e64'
    blue:    '0x7da6ff'
    magenta: '0xbb9af7'
    cyan:    '0x0db9d7'
    white:   '0xacb0d0'
